version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"

  frontend:
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
